name: $pluginName
main: $pluginMain
depend: [ Kotlin, InvFX, ProtocolLib ]
api-version: '1.16'
version: $pluginVersion
commands:
  psychics:
    aliases: ['pch']
    usage: /<command> help
    permission: 'psychics.commands'