name: $pluginName
main: $pluginMain
depend: [ Kotlin, InvFX, ProtocolLib ]
api-version: '1.16'
version: $version
author: $author
commands:
  psychics:
    aliases: [ 'psy' ]
    usage: /<command> help
    permission: 'psychics.commands'
permissions:
  psychics.reload:
    default: op